version: '3'

services:
  web:
    image: frost-http-geotech:latest
    ports:
      - 8080:8080
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - queueLoggingInterval=1000
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://192.168.178.46:6543/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true

#  database:
#    image: postgis/postgis:11-2.5-alpine
#    environment:
#      - POSTGRES_DB=sensorthings
#      - POSTGRES_USER=sensorthings
#      - POSTGRES_PASSWORD=ChangeMe
#    volumes:
#      - postgis_volume:/var/lib/postgresql/data

#volumes:
#    postgis_volume:
