--
-- PostgreSQL database dump
--

-- Dumped from database version 12.10 (Debian 12.10-1.pgdg90+1)
-- Dumped by pg_dump version 12.10 (Debian 12.10-1.pgdg90+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry, geography, and raster spatial types and functions';



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ACTUATORS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."ACTUATORS" (
    "ID" bigint NOT NULL,
    "NAME" text,
    "DESCRIPTION" text,
    "PROPERTIES" text,
    "ENCODING_TYPE" text,
    "METADATA" text
);


--
-- Name: ACTUATORS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."ACTUATORS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ACTUATORS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bh_thing_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_thing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_CollarThings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CollarThings" (
    "ID" bigint DEFAULT nextval('public.bh_thing_id_seq'::regclass) NOT NULL,
    "DESCRIPTION" text,
    "PROPERTIES" text,
    "NAME" text DEFAULT 'no name'::text
);



--
-- Name: bh_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_CollarThings_LOCATIONS; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CollarThings_LOCATIONS" (
    "BH_CollarThing_ID" bigint DEFAULT nextval('public.bh_locations_id_seq'::regclass) NOT NULL,
    "LOCATION_ID" bigint NOT NULL
);



--
-- Name: bh_foi_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_foi_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_CoreFoITypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CoreFoITypes" (
    "ID" bigint DEFAULT nextval('public.bh_foi_types_id_seq'::regclass) NOT NULL,
    "FOI_ID" bigint NOT NULL,
    "FOI_TYPE" text NOT NULL
);



--
-- Name: bh_fois_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_fois_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_CoreFoIs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CoreFoIs" (
    "ID" bigint DEFAULT nextval('public.bh_fois_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" public.geometry,
    "LENGTH" double precision,
    "PROPERTIES" text,
    "SAMPLING_ID" bigint,
    "LENGTH_UOM" text
);



--
-- Name: BH_CorePointFoITypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CorePointFoITypes" (
    "ID" bigint DEFAULT nextval('public.bh_foi_types_id_seq'::regclass) NOT NULL,
    "FOI_ID" bigint NOT NULL,
    "FOI_TYPE" text NOT NULL
);



--
-- Name: BH_CorePointFoIs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CorePointFoIs" (
    "ID" bigint DEFAULT nextval('public.bh_fois_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" public.geometry,
    "PROPERTIES" text,
    "SAMPLING_ID" bigint,
    "SAMPLED_FEATURE_ID" bigint
);



--
-- Name: BH_CoreSegmentFoITypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CoreSegmentFoITypes" (
    "ID" bigint DEFAULT nextval('public.bh_foi_types_id_seq'::regclass) NOT NULL,
    "FOI_ID" bigint NOT NULL,
    "FOI_TYPE" text NOT NULL
);



--
-- Name: BH_CoreSegmentFoIs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_CoreSegmentFoIs" (
    "ID" bigint DEFAULT nextval('public.bh_fois_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" public.geometry,
    "PROPERTIES" text,
    "SAMPLING_ID" bigint,
    "LENGTH" double precision,
    "LENGTH_UOM" text,
    "RECOVERY_PERCENTAGE" double precision,
    "SAMPLED_FEATURE_ID" bigint
);



--
-- Name: BH_HoleFoIs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_HoleFoIs" (
    "ID" bigint DEFAULT nextval('public.bh_fois_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" public.geometry,
    "LENGTH" double precision,
    "PROPERTIES" text,
    "SAMPLING_ID" bigint,
    "LENGTH_UOM" text
);


--
-- Name: BH_HolePointFoIs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_HolePointFoIs" (
    "ID" bigint DEFAULT nextval('public.bh_fois_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" public.geometry,
    "PROPERTIES" text,
    "SAMPLING_ID" bigint,
    "SAMPLED_FEATURE_ID" bigint
);



--
-- Name: BH_HoleSegmentFoIs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_HoleSegmentFoIs" (
    "ID" bigint DEFAULT nextval('public.bh_fois_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" public.geometry,
    "PROPERTIES" text,
    "SAMPLING_ID" bigint,
    "LENGTH" double precision,
    "LENGTH_UOM" text,
    "SAMPLED_FEATURE_ID" bigint
);



--
-- Name: BH_FOIS; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."BH_FOIS" AS
 SELECT "BH_HoleFoIs"."ID",
    "BH_HoleFoIs"."NAME",
    "BH_HoleFoIs"."DESCRIPTION",
    "BH_HoleFoIs"."ENCODING_TYPE",
    "BH_HoleFoIs"."FEATURE",
    ((json_build_object('length', "BH_HoleFoIs"."LENGTH", 'length_uom', "BH_HoleFoIs"."LENGTH_UOM"))::jsonb || ("BH_HoleFoIs"."PROPERTIES")::jsonb) AS "PROPERTIES"
   FROM public."BH_HoleFoIs"
UNION
 SELECT "BH_CoreFoIs"."ID",
    "BH_CoreFoIs"."NAME",
    "BH_CoreFoIs"."DESCRIPTION",
    "BH_CoreFoIs"."ENCODING_TYPE",
    "BH_CoreFoIs"."FEATURE",
    ((json_build_object('length', "BH_CoreFoIs"."LENGTH", 'length_uom', "BH_CoreFoIs"."LENGTH_UOM"))::jsonb || ("BH_CoreFoIs"."PROPERTIES")::jsonb) AS "PROPERTIES"
   FROM public."BH_CoreFoIs"
UNION
 SELECT "BH_HolePointFoIs"."ID",
    "BH_HolePointFoIs"."NAME",
    "BH_HolePointFoIs"."DESCRIPTION",
    "BH_HolePointFoIs"."ENCODING_TYPE",
    "BH_HolePointFoIs"."FEATURE",
    ("BH_HolePointFoIs"."PROPERTIES")::jsonb AS "PROPERTIES"
   FROM public."BH_HolePointFoIs"
UNION
 SELECT "BH_CorePointFoIs"."ID",
    "BH_CorePointFoIs"."NAME",
    "BH_CorePointFoIs"."DESCRIPTION",
    "BH_CorePointFoIs"."ENCODING_TYPE",
    "BH_CorePointFoIs"."FEATURE",
    ("BH_CorePointFoIs"."PROPERTIES")::jsonb AS "PROPERTIES"
   FROM public."BH_CorePointFoIs"
UNION
 SELECT "BH_HoleSegmentFoIs"."ID",
    "BH_HoleSegmentFoIs"."NAME",
    "BH_HoleSegmentFoIs"."DESCRIPTION",
    "BH_HoleSegmentFoIs"."ENCODING_TYPE",
    "BH_HoleSegmentFoIs"."FEATURE",
    ((json_build_object('length', "BH_HoleSegmentFoIs"."LENGTH", 'length_uom', "BH_HoleSegmentFoIs"."LENGTH_UOM"))::jsonb || ("BH_HoleSegmentFoIs"."PROPERTIES")::jsonb) AS "PROPERTIES"
   FROM public."BH_HoleSegmentFoIs"
UNION
 SELECT "BH_CoreSegmentFoIs"."ID",
    "BH_CoreSegmentFoIs"."NAME",
    "BH_CoreSegmentFoIs"."DESCRIPTION",
    "BH_CoreSegmentFoIs"."ENCODING_TYPE",
    "BH_CoreSegmentFoIs"."FEATURE",
    ((json_build_object('length', "BH_CoreSegmentFoIs"."LENGTH", 'length_uom', "BH_CoreSegmentFoIs"."LENGTH_UOM", 'recovery_percentage', "BH_CoreSegmentFoIs"."RECOVERY_PERCENTAGE"))::jsonb || ("BH_CoreSegmentFoIs"."PROPERTIES")::jsonb) AS "PROPERTIES"
   FROM public."BH_CoreSegmentFoIs";



--
-- Name: BH_HoleFoITypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_HoleFoITypes" (
    "ID" bigint DEFAULT nextval('public.bh_foi_types_id_seq'::regclass) NOT NULL,
    "FOI_ID" bigint NOT NULL,
    "FOI_TYPE" text NOT NULL
);



--
-- Name: BH_HolePointFoITypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_HolePointFoITypes" (
    "ID" bigint DEFAULT nextval('public.bh_foi_types_id_seq'::regclass) NOT NULL,
    "FOI_ID" bigint NOT NULL,
    "FOI_TYPE" text NOT NULL
);



--
-- Name: BH_HoleSegmentFoITypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_HoleSegmentFoITypes" (
    "ID" bigint DEFAULT nextval('public.bh_foi_types_id_seq'::regclass) NOT NULL,
    "FOI_ID" bigint NOT NULL,
    "FOI_TYPE" text NOT NULL
);



--
-- Name: BH_FOI_TYPES; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."BH_FOI_TYPES" AS
 SELECT "BH_HoleFoITypes"."ID",
    "BH_HoleFoITypes"."FOI_ID",
    "BH_HoleFoITypes"."FOI_TYPE"
   FROM public."BH_HoleFoITypes"
UNION
 SELECT "BH_HolePointFoITypes"."ID",
    "BH_HolePointFoITypes"."FOI_ID",
    "BH_HolePointFoITypes"."FOI_TYPE"
   FROM public."BH_HolePointFoITypes"
UNION
 SELECT "BH_HoleSegmentFoITypes"."ID",
    "BH_HoleSegmentFoITypes"."FOI_ID",
    "BH_HoleSegmentFoITypes"."FOI_TYPE"
   FROM public."BH_HoleSegmentFoITypes"
UNION
 SELECT "BH_CoreFoITypes"."ID",
    "BH_CoreFoITypes"."FOI_ID",
    "BH_CoreFoITypes"."FOI_TYPE"
   FROM public."BH_CoreFoITypes"
UNION
 SELECT "BH_CorePointFoITypes"."ID",
    "BH_CorePointFoITypes"."FOI_ID",
    "BH_CorePointFoITypes"."FOI_TYPE"
   FROM public."BH_CorePointFoITypes"
UNION
 SELECT "BH_CoreSegmentFoITypes"."ID",
    "BH_CoreSegmentFoITypes"."FOI_ID",
    "BH_CoreSegmentFoITypes"."FOI_TYPE"
   FROM public."BH_CoreSegmentFoITypes";



--
-- Name: bh_preparation_procedure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_preparation_procedure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_PreparationProcedure; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_PreparationProcedure" (
    "ID" bigint DEFAULT nextval('public.bh_preparation_procedure_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "LINK" text,
    "PROPERTIES" text,
    "PREPARATION_STEP_ID" bigint
);



--
-- Name: bh_preparation_step_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_preparation_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_PreparationStep; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_PreparationStep" (
    "ID" bigint DEFAULT nextval('public.bh_preparation_step_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "TIME" timestamp with time zone,
    "LINK" text,
    "PROPERTIES" text,
    "HOLE_FOI_ID" bigint,
    "CORE_FOI_ID" bigint,
    "HOLE_POINT_FOI_ID" bigint,
    "CORE_POINT_FOI_ID" bigint,
    "HOLE_SEGMENT_FOI_ID" bigint,
    "CORE_SEGMENT_FOI_ID" bigint
);



--
-- Name: bh_samplers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_samplers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_Samplers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_Samplers" (
    "ID" bigint DEFAULT nextval('public.bh_samplers_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "LINK" text,
    "SAMPLER_TYPE" text,
    "SAMPLING_PROCEDURE_ID" bigint,
    "PROPERTIES" text
);



--
-- Name: bh_sampling_procedures_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_sampling_procedures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_SamplingProcedures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_SamplingProcedures" (
    "ID" bigint DEFAULT nextval('public.bh_sampling_procedures_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "LINK" text,
    "PROPERTIES" text
);



--
-- Name: bh_samplings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bh_samplings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- Name: BH_Samplings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_Samplings" (
    "ID" bigint DEFAULT nextval('public.bh_samplings_id_seq'::regclass) NOT NULL,
    "NAME" text DEFAULT 'no name'::text,
    "DESCRIPTION" text,
    "SAMPLING_LOCATION" public.geometry,
    "TIME" timestamp with time zone,
    "TRAJECTORY_ID" bigint,
    "SAMPLING_PROCEDURE_ID" bigint,
    "SAMPLER_ID" bigint,
    "PARAMETER" text,
    "AT_POSITION" double precision,
    "FROM_POSITION" double precision,
    "TO_POSITION" double precision,
    "POSITION_UOM" text
);



--
-- Name: BH_TrajectoryThings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_TrajectoryThings" (
    "ID" bigint DEFAULT nextval('public.bh_thing_id_seq'::regclass) NOT NULL,
    "DESCRIPTION" text,
    "PROPERTIES" text,
    "NAME" text DEFAULT 'no name'::text,
    "OFFSET_HOLE" double precision,
    "OFFSET_CORE" double precision,
    "LENGTH_HOLE" double precision,
    "LENGTH_CORE" double precision,
    "UOM" text
);



--
-- Name: BH_THINGS; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."BH_THINGS" AS
 SELECT "BH_CollarThings"."ID",
    "BH_CollarThings"."DESCRIPTION",
    ("BH_CollarThings"."PROPERTIES")::jsonb AS "PROPERTIES",
    "BH_CollarThings"."NAME"
   FROM public."BH_CollarThings"
UNION
 SELECT "BH_TrajectoryThings"."ID",
    "BH_TrajectoryThings"."DESCRIPTION",
    ((json_build_object('offsetHole', "BH_TrajectoryThings"."OFFSET_HOLE", 'offsetCore', "BH_TrajectoryThings"."OFFSET_CORE", 'lengthHole', "BH_TrajectoryThings"."LENGTH_HOLE", 'lengthCore', "BH_TrajectoryThings"."LENGTH_CORE"))::jsonb || ("BH_TrajectoryThings"."PROPERTIES")::jsonb) AS "PROPERTIES",
    "BH_TrajectoryThings"."NAME"
   FROM public."BH_TrajectoryThings";



--
-- Name: BH_TrajectoryThings_LOCATIONS; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_TrajectoryThings_LOCATIONS" (
    "BH_TrajectoryThing_ID" bigint DEFAULT nextval('public.bh_locations_id_seq'::regclass) NOT NULL,
    "LOCATION_ID" bigint NOT NULL
);



--
-- Name: BH_ass_related_datastream; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_ass_related_datastream" (
    datastream_id bigint NOT NULL,
    related_datastream_id bigint NOT NULL
);



--
-- Name: BH_ass_related_observation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BH_ass_related_observation" (
    observation_id bigint NOT NULL,
    related_observation_id bigint NOT NULL
);



--
-- Name: DATASTREAMS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."DATASTREAMS" (
    "ID" bigint NOT NULL,
    "DESCRIPTION" text,
    "OBSERVATION_TYPE" text,
    "PHENOMENON_TIME_START" timestamp with time zone,
    "PHENOMENON_TIME_END" timestamp with time zone,
    "RESULT_TIME_START" timestamp with time zone,
    "RESULT_TIME_END" timestamp with time zone,
    "SENSOR_ID" bigint NOT NULL,
    "OBS_PROPERTY_ID" bigint NOT NULL,
    "THING_ID" bigint NOT NULL,
    "UNIT_NAME" character varying(255),
    "UNIT_SYMBOL" character varying(255),
    "UNIT_DEFINITION" character varying(255),
    "NAME" text DEFAULT 'no name'::text,
    "OBSERVED_AREA" public.geometry(Geometry,4326),
    "PROPERTIES" text
);


--
-- Name: DATASTREAMS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."DATASTREAMS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DATASTREAMS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LOCATIONS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."LOCATIONS" (
    "ID" bigint NOT NULL,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "LOCATION" text,
    "GEOM" public.geometry(Geometry,4326),
    "NAME" text DEFAULT 'no name'::text,
    "GEN_FOI_ID" bigint,
    "PROPERTIES" text
);



--
-- Name: OBS_PROPERTIES; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."OBS_PROPERTIES" (
    "ID" bigint NOT NULL,
    "NAME" text,
    "DEFINITION" text,
    "DESCRIPTION" text,
    "PROPERTIES" text
);



--
-- Name: THINGS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."THINGS" (
    "ID" bigint NOT NULL,
    "DESCRIPTION" text,
    "PROPERTIES" text,
    "NAME" text DEFAULT 'no name'::text
);



--
-- Name: THINGS_LOCATIONS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."THINGS_LOCATIONS" (
    "THING_ID" bigint NOT NULL,
    "LOCATION_ID" bigint NOT NULL
);



--
-- Name: DS_PROP; Type: MATERIALIZED VIEW; Schema: public; Owner: postgres
--

CREATE MATERIALIZED VIEW public."DS_PROP" AS
 SELECT d."THING_ID",
    t."NAME",
    d."ID" AS "DS_ID",
    op."NAME" AS "PROP",
    d."UNIT_NAME" AS "UOM",
    l."LOCATION"
   FROM ((((public."DATASTREAMS" d
     JOIN public."OBS_PROPERTIES" op ON ((d."OBS_PROPERTY_ID" = op."ID")))
     JOIN public."THINGS" t ON ((d."THING_ID" = t."ID")))
     JOIN public."THINGS_LOCATIONS" tl ON ((d."THING_ID" = tl."THING_ID")))
     JOIN public."LOCATIONS" l ON ((tl."LOCATION_ID" = l."ID")))
  ORDER BY op."NAME", d."THING_ID"
  WITH NO DATA;



--
-- Name: FEATURES; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."FEATURES" (
    "ID" bigint NOT NULL,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "FEATURE" text,
    "GEOM" public.geometry(Geometry,4326),
    "NAME" text DEFAULT 'no name'::text,
    "PROPERTIES" text
);


--
-- Name: FEATURES_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."FEATURES" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FEATURES_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HIST_LOCATIONS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."HIST_LOCATIONS" (
    "ID" bigint NOT NULL,
    "TIME" timestamp with time zone,
    "THING_ID" bigint NOT NULL
);



--
-- Name: HIST_LOCATIONS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."HIST_LOCATIONS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HIST_LOCATIONS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LOCATIONS_HIST_LOCATIONS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."LOCATIONS_HIST_LOCATIONS" (
    "LOCATION_ID" bigint NOT NULL,
    "HIST_LOCATION_ID" bigint NOT NULL
);



--
-- Name: LOCATIONS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."LOCATIONS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LOCATIONS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




--
-- Name: OBSERVATIONS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."OBSERVATIONS" (
    "ID" bigint NOT NULL,
    "PHENOMENON_TIME_START" timestamp with time zone,
    "PHENOMENON_TIME_END" timestamp with time zone,
    "RESULT_TIME" timestamp with time zone,
    "RESULT_NUMBER" double precision,
    "RESULT_STRING" text,
    "RESULT_QUALITY" text,
    "VALID_TIME_START" timestamp with time zone,
    "VALID_TIME_END" timestamp with time zone,
    "PARAMETERS" text,
    "DATASTREAM_ID" bigint,
    "FEATURE_ID" bigint NOT NULL,
    "RESULT_TYPE" smallint,
    "RESULT_JSON" text,
    "RESULT_BOOLEAN" boolean
);




--
-- Name: OBSERVATIONS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."OBSERVATIONS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OBSERVATIONS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OBS_PROPERTIES_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."OBS_PROPERTIES" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OBS_PROPERTIES_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: SENSORS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."SENSORS" (
    "ID" bigint NOT NULL,
    "DESCRIPTION" text,
    "ENCODING_TYPE" text,
    "METADATA" text,
    "NAME" text DEFAULT 'no name'::text,
    "PROPERTIES" text
);



--
-- Name: SENSORS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."SENSORS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SENSORS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: TASKINGCAPABILITIES; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."TASKINGCAPABILITIES" (
    "ID" bigint NOT NULL,
    "NAME" text,
    "DESCRIPTION" text,
    "PROPERTIES" text,
    "TASKING_PARAMETERS" text,
    "ACTUATOR_ID" bigint NOT NULL,
    "THING_ID" bigint NOT NULL
);


--
-- Name: TASKINGCAPABILITIES_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."TASKINGCAPABILITIES" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TASKINGCAPABILITIES_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TASKS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."TASKS" (
    "ID" bigint NOT NULL,
    "CREATION_TIME" timestamp with time zone,
    "TASKING_PARAMETERS" text,
    "TASKINGCAPABILITY_ID" bigint NOT NULL
);



--
-- Name: TASKS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."TASKS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TASKS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: THINGS_ID_seq; Type: SEQUENCE; Schema: public; Owner: airthings
--

ALTER TABLE public."THINGS" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."THINGS_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: USERS; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."USERS" (
    "USER_NAME" character varying(25) NOT NULL,
    "USER_PASS" character varying(255)
);



--
-- Name: USER_ROLES; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public."USER_ROLES" (
    "USER_NAME" character varying(25) NOT NULL,
    "ROLE_NAME" character varying(15) NOT NULL
);



--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);



--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: airthings
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);



--
-- Name: ACTUATORS ACTUATORS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."ACTUATORS"
    ADD CONSTRAINT "ACTUATORS_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_CollarThings_LOCATIONS BH_CollarThings_LOCATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CollarThings_LOCATIONS"
    ADD CONSTRAINT "BH_CollarThings_LOCATIONS_PKEY" PRIMARY KEY ("BH_CollarThing_ID", "LOCATION_ID");


--
-- Name: BH_CollarThings BH_CollarThings_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CollarThings"
    ADD CONSTRAINT "BH_CollarThings_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_CoreFoIs BH_CoreFoIs_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreFoIs"
    ADD CONSTRAINT "BH_CoreFoIs_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_CorePointFoIs BH_CorePointFoIs_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CorePointFoIs"
    ADD CONSTRAINT "BH_CorePointFoIs_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_CoreSegmentFoIs BH_CoreSegmentFoIs_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreSegmentFoIs"
    ADD CONSTRAINT "BH_CoreSegmentFoIs_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_HoleFoIs BH_HoleFoI_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleFoIs"
    ADD CONSTRAINT "BH_HoleFoI_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_HolePointFoIs BH_HolePointFoI_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HolePointFoIs"
    ADD CONSTRAINT "BH_HolePointFoI_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_HoleSegmentFoIs BH_HoleSegmentFoI_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleSegmentFoIs"
    ADD CONSTRAINT "BH_HoleSegmentFoI_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_PreparationProcedure BH_PreparationProcedure_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationProcedure"
    ADD CONSTRAINT "BH_PreparationProcedure_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_Samplers BH_Samplers_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_Samplers"
    ADD CONSTRAINT "BH_Samplers_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_SamplingProcedures BH_SamplingProcedures_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_SamplingProcedures"
    ADD CONSTRAINT "BH_SamplingProcedures_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_Samplings BH_Samplings_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_Samplings"
    ADD CONSTRAINT "BH_Samplings_PKEY" PRIMARY KEY ("ID");


--
-- Name: BH_TrajectoryThings_LOCATIONS BH_TrajectoryThings_LOCATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_TrajectoryThings_LOCATIONS"
    ADD CONSTRAINT "BH_TrajectoryThings_LOCATIONS_PKEY" PRIMARY KEY ("BH_TrajectoryThing_ID", "LOCATION_ID");


--
-- Name: BH_TrajectoryThings BH_TrajectoryThings_PKEY; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_TrajectoryThings"
    ADD CONSTRAINT "BH_TrajectoryThings_PKEY" PRIMARY KEY ("ID");


--
-- Name: DATASTREAMS DATASTREAMS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."DATASTREAMS"
    ADD CONSTRAINT "DATASTREAMS_PKEY" PRIMARY KEY ("ID");


--
-- Name: FEATURES FEATURES_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."FEATURES"
    ADD CONSTRAINT "FEATURES_PKEY" PRIMARY KEY ("ID");


--
-- Name: HIST_LOCATIONS HIST_LOCATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."HIST_LOCATIONS"
    ADD CONSTRAINT "HIST_LOCATIONS_PKEY" PRIMARY KEY ("ID");


--
-- Name: LOCATIONS_HIST_LOCATIONS LOCATIONS_HIST_LOCATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."LOCATIONS_HIST_LOCATIONS"
    ADD CONSTRAINT "LOCATIONS_HIST_LOCATIONS_PKEY" PRIMARY KEY ("LOCATION_ID", "HIST_LOCATION_ID");


--
-- Name: LOCATIONS LOCATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."LOCATIONS"
    ADD CONSTRAINT "LOCATIONS_PKEY" PRIMARY KEY ("ID");



--
-- Name: OBSERVATIONS OBSERVATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."OBSERVATIONS"
    ADD CONSTRAINT "OBSERVATIONS_PKEY" PRIMARY KEY ("ID");


--
-- Name: OBS_PROPERTIES OBS_PROPERTIES_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."OBS_PROPERTIES"
    ADD CONSTRAINT "OBS_PROPERTIES_PKEY" PRIMARY KEY ("ID");


--
-- Name: SENSORS SENSORS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."SENSORS"
    ADD CONSTRAINT "SENSORS_PKEY" PRIMARY KEY ("ID");


--
-- Name: TASKINGCAPABILITIES TASKINGCAPABILITIES_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."TASKINGCAPABILITIES"
    ADD CONSTRAINT "TASKINGCAPABILITIES_PKEY" PRIMARY KEY ("ID");


--
-- Name: TASKS TASKS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."TASKS"
    ADD CONSTRAINT "TASKS_PKEY" PRIMARY KEY ("ID");


--
-- Name: THINGS_LOCATIONS THINGS_LOCATIONS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."THINGS_LOCATIONS"
    ADD CONSTRAINT "THINGS_LOCATIONS_PKEY" PRIMARY KEY ("THING_ID", "LOCATION_ID");


--
-- Name: THINGS THINGS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."THINGS"
    ADD CONSTRAINT "THINGS_PKEY" PRIMARY KEY ("ID");


--
-- Name: USERS USERS_PKEY; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."USERS"
    ADD CONSTRAINT "USERS_PKEY" PRIMARY KEY ("USER_NAME");


--
-- Name: USER_ROLES USER_ROLES_pkey; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."USER_ROLES"
    ADD CONSTRAINT "USER_ROLES_pkey" PRIMARY KEY ("USER_NAME", "ROLE_NAME");


--
-- Name: BH_CoreFoITypes bh_core_foi_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreFoITypes"
    ADD CONSTRAINT bh_core_foi_types_pkey PRIMARY KEY ("ID");


--
-- Name: BH_CorePointFoITypes bh_core_point_foi_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CorePointFoITypes"
    ADD CONSTRAINT bh_core_point_foi_types_pkey PRIMARY KEY ("ID");


--
-- Name: BH_CoreSegmentFoITypes bh_core_segment_foi_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreSegmentFoITypes"
    ADD CONSTRAINT bh_core_segment_foi_types_pkey PRIMARY KEY ("ID");


--
-- Name: BH_HoleFoITypes bh_hole_foi_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleFoITypes"
    ADD CONSTRAINT bh_hole_foi_types_pkey PRIMARY KEY ("ID");


--
-- Name: BH_HolePointFoITypes bh_hole_point_foi_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HolePointFoITypes"
    ADD CONSTRAINT bh_hole_point_foi_types_pkey PRIMARY KEY ("ID");


--
-- Name: BH_HoleSegmentFoITypes bh_hole_segment_foi_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleSegmentFoITypes"
    ADD CONSTRAINT bh_hole_segment_foi_types_pkey PRIMARY KEY ("ID");


--
-- Name: BH_ass_related_datastream bh_related_datastream_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_ass_related_datastream"
    ADD CONSTRAINT bh_related_datastream_pkey PRIMARY KEY (datastream_id, related_datastream_id);


--
-- Name: BH_ass_related_observation bh_related_observation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_ass_related_observation"
    ADD CONSTRAINT bh_related_observation_pkey PRIMARY KEY (observation_id, related_observation_id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: BH_CollarThings_LOCATIONS_BH_CollarThing_ID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "BH_CollarThings_LOCATIONS_BH_CollarThing_ID" ON public."BH_CollarThings_LOCATIONS" USING btree ("BH_CollarThing_ID");


--
-- Name: BH_CollarThings_LOCATIONS_LOCATION_ID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "BH_CollarThings_LOCATIONS_LOCATION_ID" ON public."BH_CollarThings_LOCATIONS" USING btree ("LOCATION_ID");


--
-- Name: BH_TrajectoryThings_LOCATIONS_BH_TrajectoryThing_ID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "BH_TrajectoryThings_LOCATIONS_BH_TrajectoryThing_ID" ON public."BH_TrajectoryThings_LOCATIONS" USING btree ("BH_TrajectoryThing_ID");


--
-- Name: BH_TrajectoryThings_LOCATIONS_LOCATION_ID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "BH_TrajectoryThings_LOCATIONS_LOCATION_ID" ON public."BH_TrajectoryThings_LOCATIONS" USING btree ("LOCATION_ID");


--
-- Name: DATASTREAMS_OBS_PROPERTY_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "DATASTREAMS_OBS_PROPERTY_ID" ON public."DATASTREAMS" USING btree ("OBS_PROPERTY_ID");


--
-- Name: DATASTREAMS_SENSOR_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "DATASTREAMS_SENSOR_ID" ON public."DATASTREAMS" USING btree ("SENSOR_ID");


--
-- Name: DATASTREAMS_THING_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "DATASTREAMS_THING_ID" ON public."DATASTREAMS" USING btree ("THING_ID");


--
-- Name: DS_PROP_ID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "DS_PROP_ID" ON public."DS_PROP" USING btree ("PROP");


--
-- Name: DS_THING_ID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "DS_THING_ID" ON public."DS_PROP" USING btree ("THING_ID");


--
-- Name: HIST_LOCATIONS_THING_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "HIST_LOCATIONS_THING_ID" ON public."HIST_LOCATIONS" USING btree ("THING_ID");


--
-- Name: LOCATIONS_HIST_LOCATIONS_HIST_LOCATION_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "LOCATIONS_HIST_LOCATIONS_HIST_LOCATION_ID" ON public."LOCATIONS_HIST_LOCATIONS" USING btree ("HIST_LOCATION_ID");


--
-- Name: LOCATIONS_HIST_LOCATIONS_LOCATION_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "LOCATIONS_HIST_LOCATIONS_LOCATION_ID" ON public."LOCATIONS_HIST_LOCATIONS" USING btree ("LOCATION_ID");



--
-- Name: OBS-DS_ID-PHTIME_SE-O_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "OBS-DS_ID-PHTIME_SE-O_ID" ON public."OBSERVATIONS" USING btree ("DATASTREAM_ID", "PHENOMENON_TIME_START", "PHENOMENON_TIME_END");


--
-- Name: OBS-PHTIME-DESC_SE-O_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "OBS-PHTIME-DESC_SE-O_ID" ON public."OBSERVATIONS" USING btree ("PHENOMENON_TIME_START" DESC, "PHENOMENON_TIME_END" DESC);


--
-- Name: OBSERVATIONS_DATASTREAM_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "OBSERVATIONS_DATASTREAM_ID" ON public."OBSERVATIONS" USING btree ("DATASTREAM_ID");


--
-- Name: OBSERVATIONS_FEATURE_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "OBSERVATIONS_FEATURE_ID" ON public."OBSERVATIONS" USING btree ("FEATURE_ID");



--
-- Name: TASKINGCAPABILITIES_ACTUATOR_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "TASKINGCAPABILITIES_ACTUATOR_ID" ON public."TASKINGCAPABILITIES" USING btree ("ACTUATOR_ID");


--
-- Name: TASKINGCAPABILITIES_THING_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "TASKINGCAPABILITIES_THING_ID" ON public."TASKINGCAPABILITIES" USING btree ("THING_ID");


--
-- Name: TASKS_TASKINGCAPABILITY_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "TASKS_TASKINGCAPABILITY_ID" ON public."TASKS" USING btree ("TASKINGCAPABILITY_ID");


--
-- Name: THINGS_LOCATIONS_LOCATION_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "THINGS_LOCATIONS_LOCATION_ID" ON public."THINGS_LOCATIONS" USING btree ("LOCATION_ID");


--
-- Name: THINGS_LOCATIONS_THING_ID; Type: INDEX; Schema: public; Owner: airthings
--

CREATE INDEX "THINGS_LOCATIONS_THING_ID" ON public."THINGS_LOCATIONS" USING btree ("THING_ID");



--
-- Name: BH_CollarThings_LOCATIONS BH_CollarThings_LOCATIONS_BH_CollarThing_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CollarThings_LOCATIONS"
    ADD CONSTRAINT "BH_CollarThings_LOCATIONS_BH_CollarThing_ID_FKEY" FOREIGN KEY ("BH_CollarThing_ID") REFERENCES public."BH_CollarThings"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_CollarThings_LOCATIONS BH_CollarThings_LOCATIONS_LOCATION_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CollarThings_LOCATIONS"
    ADD CONSTRAINT "BH_CollarThings_LOCATIONS_LOCATION_ID_FKEY" FOREIGN KEY ("LOCATION_ID") REFERENCES public."LOCATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_CoreFoIs BH_CoreFoIs_SAMPLING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreFoIs"
    ADD CONSTRAINT "BH_CoreFoIs_SAMPLING_ID_FKEY" FOREIGN KEY ("SAMPLING_ID") REFERENCES public."BH_Samplings"("ID");


--
-- Name: BH_CorePointFoIs BH_CorePointFoIs_SAMPLED_FEATURE_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CorePointFoIs"
    ADD CONSTRAINT "BH_CorePointFoIs_SAMPLED_FEATURE_ID_FKEY" FOREIGN KEY ("SAMPLED_FEATURE_ID") REFERENCES public."BH_CoreFoIs"("ID");


--
-- Name: BH_CorePointFoIs BH_CorePointFoIs_SAMPLING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CorePointFoIs"
    ADD CONSTRAINT "BH_CorePointFoIs_SAMPLING_ID_FKEY" FOREIGN KEY ("SAMPLING_ID") REFERENCES public."BH_Samplings"("ID");


--
-- Name: BH_CoreSegmentFoIs BH_CoreSegmentFoIs_SAMPLED_FEATURE_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreSegmentFoIs"
    ADD CONSTRAINT "BH_CoreSegmentFoIs_SAMPLED_FEATURE_ID_FKEY" FOREIGN KEY ("SAMPLED_FEATURE_ID") REFERENCES public."BH_CoreFoIs"("ID");


--
-- Name: BH_CoreSegmentFoIs BH_CoreSegmentFoIs_SAMPLING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreSegmentFoIs"
    ADD CONSTRAINT "BH_CoreSegmentFoIs_SAMPLING_ID_FKEY" FOREIGN KEY ("SAMPLING_ID") REFERENCES public."BH_Samplings"("ID");


--
-- Name: BH_HoleFoIs BH_HoleFoI_SAMPLING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleFoIs"
    ADD CONSTRAINT "BH_HoleFoI_SAMPLING_ID_FKEY" FOREIGN KEY ("SAMPLING_ID") REFERENCES public."BH_Samplings"("ID");


--
-- Name: BH_HolePointFoIs BH_HolePointFoI_SAMPLING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HolePointFoIs"
    ADD CONSTRAINT "BH_HolePointFoI_SAMPLING_ID_FKEY" FOREIGN KEY ("SAMPLING_ID") REFERENCES public."BH_Samplings"("ID");


--
-- Name: BH_HolePointFoIs BH_HolePointFoIs_SAMPLED_FEATURE_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HolePointFoIs"
    ADD CONSTRAINT "BH_HolePointFoIs_SAMPLED_FEATURE_ID_FKEY" FOREIGN KEY ("SAMPLED_FEATURE_ID") REFERENCES public."BH_HoleFoIs"("ID");


--
-- Name: BH_HoleSegmentFoIs BH_HoleSegmentFoI_SAMPLING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleSegmentFoIs"
    ADD CONSTRAINT "BH_HoleSegmentFoI_SAMPLING_ID_FKEY" FOREIGN KEY ("SAMPLING_ID") REFERENCES public."BH_Samplings"("ID");


--
-- Name: BH_HoleSegmentFoIs BH_HoleSegmentFoIs_SAMPLED_FEATURE_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleSegmentFoIs"
    ADD CONSTRAINT "BH_HoleSegmentFoIs_SAMPLED_FEATURE_ID_FKEY" FOREIGN KEY ("SAMPLED_FEATURE_ID") REFERENCES public."BH_HoleFoIs"("ID");


--
-- Name: BH_PreparationProcedure BH_PreparationProcedure_PREPARATION_STEP_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationProcedure"
    ADD CONSTRAINT "BH_PreparationProcedure_PREPARATION_STEP_ID_FKEY" FOREIGN KEY ("PREPARATION_STEP_ID") REFERENCES public."BH_PreparationStep"("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_CORE_FOI_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_CORE_FOI_ID_FKEY" FOREIGN KEY ("CORE_FOI_ID") REFERENCES public."BH_CoreFoIs"("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_CORE_POINT_FOI_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_CORE_POINT_FOI_ID_FKEY" FOREIGN KEY ("CORE_POINT_FOI_ID") REFERENCES public."BH_CorePointFoIs"("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_CORE_SEGMENT_FOI_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_CORE_SEGMENT_FOI_ID_FKEY" FOREIGN KEY ("CORE_SEGMENT_FOI_ID") REFERENCES public."BH_CoreSegmentFoIs"("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_HOLE_FOI_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_HOLE_FOI_ID_FKEY" FOREIGN KEY ("HOLE_FOI_ID") REFERENCES public."BH_HoleFoIs"("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_HOLE_POINT_FOI_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_HOLE_POINT_FOI_ID_FKEY" FOREIGN KEY ("HOLE_POINT_FOI_ID") REFERENCES public."BH_HolePointFoIs"("ID");


--
-- Name: BH_PreparationStep BH_PreparationStep_HOLE_SEGMENT_FOI_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_PreparationStep"
    ADD CONSTRAINT "BH_PreparationStep_HOLE_SEGMENT_FOI_ID_FKEY" FOREIGN KEY ("HOLE_SEGMENT_FOI_ID") REFERENCES public."BH_HoleSegmentFoIs"("ID");


--
-- Name: BH_Samplers BH_Samplers_SAMPLING_PROCEDURE_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_Samplers"
    ADD CONSTRAINT "BH_Samplers_SAMPLING_PROCEDURE_ID_FKEY" FOREIGN KEY ("SAMPLING_PROCEDURE_ID") REFERENCES public."BH_SamplingProcedures"("ID");


--
-- Name: BH_Samplings BH_Samplings_TRAJECTORY_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_Samplings"
    ADD CONSTRAINT "BH_Samplings_TRAJECTORY_ID_FKEY" FOREIGN KEY ("TRAJECTORY_ID") REFERENCES public."BH_TrajectoryThings"("ID");


--
-- Name: BH_TrajectoryThings_LOCATIONS BH_TrajectoryThings_LOCATIONS_BH_TrajectoryThing_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_TrajectoryThings_LOCATIONS"
    ADD CONSTRAINT "BH_TrajectoryThings_LOCATIONS_BH_TrajectoryThing_ID_FKEY" FOREIGN KEY ("BH_TrajectoryThing_ID") REFERENCES public."BH_TrajectoryThings"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_TrajectoryThings_LOCATIONS BH_TrajectoryThings_LOCATIONS_LOCATION_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_TrajectoryThings_LOCATIONS"
    ADD CONSTRAINT "BH_TrajectoryThings_LOCATIONS_LOCATION_ID_FKEY" FOREIGN KEY ("LOCATION_ID") REFERENCES public."LOCATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: DATASTREAMS DATASTREAMS_OBS_PROPERTY_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."DATASTREAMS"
    ADD CONSTRAINT "DATASTREAMS_OBS_PROPERTY_ID_FKEY" FOREIGN KEY ("OBS_PROPERTY_ID") REFERENCES public."OBS_PROPERTIES"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: DATASTREAMS DATASTREAMS_SENSOR_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."DATASTREAMS"
    ADD CONSTRAINT "DATASTREAMS_SENSOR_ID_FKEY" FOREIGN KEY ("SENSOR_ID") REFERENCES public."SENSORS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: DATASTREAMS DATASTREAMS_THING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."DATASTREAMS"
    ADD CONSTRAINT "DATASTREAMS_THING_ID_FKEY" FOREIGN KEY ("THING_ID") REFERENCES public."THINGS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: HIST_LOCATIONS HIST_LOCATIONS_THING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."HIST_LOCATIONS"
    ADD CONSTRAINT "HIST_LOCATIONS_THING_ID_FKEY" FOREIGN KEY ("THING_ID") REFERENCES public."THINGS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: LOCATIONS_HIST_LOCATIONS LOCATIONS_HIST_LOCATIONS_HIST_LOCATION_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."LOCATIONS_HIST_LOCATIONS"
    ADD CONSTRAINT "LOCATIONS_HIST_LOCATIONS_HIST_LOCATION_ID_FKEY" FOREIGN KEY ("HIST_LOCATION_ID") REFERENCES public."HIST_LOCATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: LOCATIONS_HIST_LOCATIONS LOCATIONS_HIST_LOCATIONS_LOCATION_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."LOCATIONS_HIST_LOCATIONS"
    ADD CONSTRAINT "LOCATIONS_HIST_LOCATIONS_LOCATION_ID_FKEY" FOREIGN KEY ("LOCATION_ID") REFERENCES public."LOCATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;



--
-- Name: OBSERVATIONS OBSERVATIONS_DATASTREAM_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."OBSERVATIONS"
    ADD CONSTRAINT "OBSERVATIONS_DATASTREAM_ID_FKEY" FOREIGN KEY ("DATASTREAM_ID") REFERENCES public."DATASTREAMS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: OBSERVATIONS OBSERVATIONS_FEATURE_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."OBSERVATIONS"
    ADD CONSTRAINT "OBSERVATIONS_FEATURE_ID_FKEY" FOREIGN KEY ("FEATURE_ID") REFERENCES public."FEATURES"("ID") ON UPDATE CASCADE ON DELETE CASCADE;




--
-- Name: TASKINGCAPABILITIES TASKINGCAPABILITIES_ACTUATOR_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."TASKINGCAPABILITIES"
    ADD CONSTRAINT "TASKINGCAPABILITIES_ACTUATOR_ID_FKEY" FOREIGN KEY ("ACTUATOR_ID") REFERENCES public."ACTUATORS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: TASKINGCAPABILITIES TASKINGCAPABILITIES_THING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."TASKINGCAPABILITIES"
    ADD CONSTRAINT "TASKINGCAPABILITIES_THING_ID_FKEY" FOREIGN KEY ("THING_ID") REFERENCES public."THINGS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: TASKS TASKS_TASKINGCAPABILITY_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."TASKS"
    ADD CONSTRAINT "TASKS_TASKINGCAPABILITY_ID_FKEY" FOREIGN KEY ("TASKINGCAPABILITY_ID") REFERENCES public."TASKINGCAPABILITIES"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: THINGS_LOCATIONS THINGS_LOCATIONS_LOCATION_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."THINGS_LOCATIONS"
    ADD CONSTRAINT "THINGS_LOCATIONS_LOCATION_ID_FKEY" FOREIGN KEY ("LOCATION_ID") REFERENCES public."LOCATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: THINGS_LOCATIONS THINGS_LOCATIONS_THING_ID_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."THINGS_LOCATIONS"
    ADD CONSTRAINT "THINGS_LOCATIONS_THING_ID_FKEY" FOREIGN KEY ("THING_ID") REFERENCES public."THINGS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: USER_ROLES USER_ROLES_USERS_FKEY; Type: FK CONSTRAINT; Schema: public; Owner: airthings
--

ALTER TABLE ONLY public."USER_ROLES"
    ADD CONSTRAINT "USER_ROLES_USERS_FKEY" FOREIGN KEY ("USER_NAME") REFERENCES public."USERS"("USER_NAME") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_CoreFoITypes bh_core_foi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreFoITypes"
    ADD CONSTRAINT bh_core_foi_id_fkey FOREIGN KEY ("FOI_ID") REFERENCES public."BH_CoreFoIs"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_CorePointFoITypes bh_core_point_foi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CorePointFoITypes"
    ADD CONSTRAINT bh_core_point_foi_id_fkey FOREIGN KEY ("FOI_ID") REFERENCES public."BH_CorePointFoIs"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_CoreSegmentFoITypes bh_core_segment_foi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_CoreSegmentFoITypes"
    ADD CONSTRAINT bh_core_segment_foi_id_fkey FOREIGN KEY ("FOI_ID") REFERENCES public."BH_CoreSegmentFoIs"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_HoleFoITypes bh_hole_foi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleFoITypes"
    ADD CONSTRAINT bh_hole_foi_id_fkey FOREIGN KEY ("FOI_ID") REFERENCES public."BH_HoleFoIs"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_HolePointFoITypes bh_hole_point_foi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HolePointFoITypes"
    ADD CONSTRAINT bh_hole_point_foi_id_fkey FOREIGN KEY ("FOI_ID") REFERENCES public."BH_HolePointFoIs"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_HoleSegmentFoITypes bh_hole_segment_foi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_HoleSegmentFoITypes"
    ADD CONSTRAINT bh_hole_segment_foi_id_fkey FOREIGN KEY ("FOI_ID") REFERENCES public."BH_HoleSegmentFoIs"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_ass_related_datastream bh_related_datastream_datastream_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_ass_related_datastream"
    ADD CONSTRAINT bh_related_datastream_datastream_id_fkey FOREIGN KEY (datastream_id) REFERENCES public."DATASTREAMS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_ass_related_datastream bh_related_datastream_related_datastream_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_ass_related_datastream"
    ADD CONSTRAINT bh_related_datastream_related_datastream_id_fkey FOREIGN KEY (related_datastream_id) REFERENCES public."DATASTREAMS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_ass_related_observation bh_related_observation_observation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_ass_related_observation"
    ADD CONSTRAINT bh_related_observation_observation_id_fkey FOREIGN KEY (observation_id) REFERENCES public."OBSERVATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_ass_related_observation bh_related_observation_related_observation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_ass_related_observation"
    ADD CONSTRAINT bh_related_observation_related_observation_id_fkey FOREIGN KEY (related_observation_id) REFERENCES public."OBSERVATIONS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: BH_Samplings bh_samplings_sampler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_Samplings"
    ADD CONSTRAINT bh_samplings_sampler_id_fkey FOREIGN KEY ("SAMPLER_ID") REFERENCES public."BH_Samplers"("ID");


--
-- Name: BH_Samplings bh_samplings_sampling_procedure_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BH_Samplings"
    ADD CONSTRAINT bh_samplings_sampling_procedure_id_fkey FOREIGN KEY ("SAMPLING_PROCEDURE_ID") REFERENCES public."BH_SamplingProcedures"("ID");


--
-- PostgreSQL database dump complete
--

